import React, { createContext, useContext, useState } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  'pt-br': {
    'app.title': 'MaterialShare Pro',
    'auth.login': 'Entrar',
    'auth.register': 'Cadastrar',
    'auth.hint': 'Contas Demo: admin@demo.com, client@demo.com, distributor@demo.com, consultant@demo.com (Senha: 123456)',
    
    // Landing Page Texts
    'landing.client.title': 'Bem-vindo à Área do Cliente',
    'landing.client.desc': 'Tenha acesso exclusivo a toda documentação técnica e novidades dos nossos produtos.',
    'landing.client.benefit.1': 'Download de Manuais e Certificados',
    'landing.client.benefit.2': 'Visualização de Catálogos em Alta Definição',
    'landing.client.benefit.3': 'Acesso a Vídeos de Instrução e Uso',

    'landing.distributor.title': 'Portal do Parceiro Distribuidor',
    'landing.distributor.desc': 'Acelere suas vendas com ferramentas de marketing e tabelas comerciais atualizadas.',
    'landing.distributor.benefit.1': 'Acesso a Tabelas de Preços Confidenciais',
    'landing.distributor.benefit.2': 'Download de Kits de Marketing (Posts, Banners)',
    'landing.distributor.benefit.3': 'Prioridade em Lançamentos de Produtos',

    'landing.consultant.title': 'Academia de Vendas',
    'landing.consultant.desc': 'Domine o portfólio e feche mais negócios com nossos materiais de apoio.',
    'landing.consultant.benefit.1': 'Treinamentos Técnicos e Comerciais',
    'landing.consultant.benefit.2': 'Scripts de Vendas e Argumentação',
    'landing.consultant.benefit.3': 'Materiais de Apoio para Apresentações',
    
    'dashboard.title': 'Materiais Disponíveis',
    'admin.title': 'Painel Administrativo',
    'common.logout': 'Sair',
    'role.client': 'Cliente',
    'role.distributor': 'Distribuidor',
    'role.consultant': 'Consultor',
    'role.super_admin': 'Super Admin',
    'material.type.pdf': 'Documento PDF',
    'material.type.image': 'Imagem',
    'material.type.video': 'Vídeo',
    'no.materials': 'Nenhum material encontrado com os filtros atuais.',
    'add.material': 'Adicionar Material',
    'edit.material': 'Editar Material',
    'delete': 'Excluir',
    'edit': 'Editar',
    'view': 'Visualizar',
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'title': 'Título',
    'type': 'Tipo',
    'permissions': 'Permissões',
    'actions': 'Ações',
    'status': 'Status',
    'active': 'Ativo',
    'inactive': 'Inativo',
    'manage.assets': 'Gerenciar Arquivos',
    'asset.url': 'URL do Arquivo',
    'asset.subtitle': 'URL da Legenda',
    'edit.assets.title': 'Gerenciar Versões: ',
    'empty.url.hint': 'Deixe a URL vazia para remover a versão deste idioma.',
    'url.placeholder.pdf': 'URL direta ou Link do Google Drive',
    'url.placeholder.image': 'URL direta ou Link do Google Drive',
    'url.placeholder.video': 'YouTube, Vimeo, Drive ou URL MP4 direta',
    'url.help.text': 'Aceita links de compartilhamento do Google Drive, YouTube e Vimeo.',
    'search.placeholder': 'Buscar por nome...',
    'filter.title': 'Categorias',
    'filter.all': 'Todos os Materiais',
    'filter.pdf': 'Documentos PDF',
    'filter.image': 'Imagens',
    'filter.video': 'Vídeos',
    // User Management
    'tab.materials': 'Materiais',
    'tab.users': 'Usuários',
    'tab.settings': 'Configurações',
    'tab.analytics': 'Métricas',
    'user.edit': 'Editar Usuário',
    'user.filter.all': 'Todos os Perfis',
    'user.filter.status.all': 'Todos os Status',
    'user.status.pending': 'Pendente',
    'user.status.active': 'Ativo',
    'user.status.inactive': 'Inativo',
    'user.status.rejected': 'Rejeitado',
    'user.action.approve': 'Aprovar',
    'user.action.reject': 'Reprovar',
    'user.action.inactivate': 'Inativar',
    'user.action.delete': 'Excluir Usuário',
    'user.invite': 'Convites de Cadastro',
    'user.invite.copy': 'Copiar Link',
    'user.invite.copied': 'Copiado!',
    'user.access.types': 'Permissões de Tipos de Arquivo',
    'user.access.hint': 'Se nenhum for selecionado, o usuário terá acesso a todos os tipos permitidos para seu perfil.',
    // Communication
    'comm.title': 'Enviar Mensagem',
    'comm.send': 'Enviar',
    'comm.success': 'Mensagem enviada com sucesso para o fluxo N8N!',
    'comm.type.email': 'E-mail',
    'comm.type.whatsapp': 'WhatsApp',
    'comm.email.subject': 'Assunto',
    'comm.email.subtitle': 'Subtítulo',
    'comm.email.body': 'Corpo do E-mail',
    'comm.wa.type': 'Tipo de Mensagem',
    'comm.wa.text': 'Apenas Texto',
    'comm.wa.file': 'Texto + Arquivo',
    'comm.wa.message': 'Mensagem',
    'comm.file.url': 'URL do Arquivo/Anexo',
    // Confirmation Modal
    'confirm.delete.title': 'Confirmar Exclusão',
    'confirm.delete.message': 'Tem certeza que deseja excluir este item? Esta ação é irreversível.',
    'confirm.delete.confirm': 'Sim, Excluir',
    // Analytics
    'analytics.total.views': 'Total de Visualizações',
    'analytics.unique.users': 'Usuários Únicos',
    'analytics.top.material': 'Material Mais Acessado',
    'analytics.col.views': 'Visualizações',
    'analytics.col.users': 'Usuários',
    'analytics.col.last_access': 'Último Acesso',
    'analytics.detail.title': 'Histórico de Acesso',
    'analytics.detail.user': 'Usuário',
    'analytics.detail.date': 'Data/Hora',
    'analytics.detail.lang': 'Idioma',
    'analytics.empty': 'Nenhum acesso registrado ainda.',
    'analytics.rank.materials': 'Top 5 Materiais',
    'analytics.rank.users': 'Top 5 Usuários Ativos',
    'analytics.filter.type': 'Filtrar por Tipo de Documento',
    'analytics.filter.role': 'Filtrar por Perfil de Usuário',
  },
  'en-us': {
    'app.title': 'MaterialShare Pro',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.hint': 'Demo Accounts: admin@demo.com, client@demo.com, distributor@demo.com, consultant@demo.com (Pass: 123456)',
    // Landing Page Texts
    'landing.client.title': 'Welcome to Client Area',
    'landing.client.desc': 'Get exclusive access to all technical documentation and news about our products.',
    'landing.client.benefit.1': 'Download Manuals and Certificates',
    'landing.client.benefit.2': 'View High Definition Catalogs',
    'landing.client.benefit.3': 'Access Instruction and Usage Videos',

    'landing.distributor.title': 'Distributor Partner Portal',
    'landing.distributor.desc': 'Accelerate your sales with marketing tools and updated commercial tables.',
    'landing.distributor.benefit.1': 'Access Confidential Price Lists',
    'landing.distributor.benefit.2': 'Download Marketing Kits (Posts, Banners)',
    'landing.distributor.benefit.3': 'Priority on Product Launches',

    'landing.consultant.title': 'Sales Academy',
    'landing.consultant.desc': 'Master the portfolio and close more deals with our support materials.',
    'landing.consultant.benefit.1': 'Technical and Commercial Training',
    'landing.consultant.benefit.2': 'Sales Scripts and Argumentation',
    'landing.consultant.benefit.3': 'Support Materials for Presentations',

    'dashboard.title': 'Available Materials',
    'admin.title': 'Admin Panel',
    'common.logout': 'Logout',
    'role.client': 'Client',
    'role.distributor': 'Distributor',
    'role.consultant': 'Consultant',
    'role.super_admin': 'Super Admin',
    'material.type.pdf': 'PDF Document',
    'material.type.image': 'Image',
    'material.type.video': 'Video',
    'no.materials': 'No materials found matching current filters.',
    'add.material': 'Add Material',
    'edit.material': 'Edit Material',
    'delete': 'Delete',
    'edit': 'Edit',
    'view': 'View',
    'save': 'Save',
    'cancel': 'Cancel',
    'title': 'Title',
    'type': 'Type',
    'permissions': 'Permissions',
    'actions': 'Actions',
    'status': 'Status',
    'active': 'Active',
    'inactive': 'Inactive',
    'manage.assets': 'Manage Files',
    'asset.url': 'File URL',
    'asset.subtitle': 'Subtitle URL',
    'edit.assets.title': 'Manage Versions: ',
    'empty.url.hint': 'Leave URL empty to remove the version for this language.',
    'url.placeholder.pdf': 'Direct URL or Google Drive Link',
    'url.placeholder.image': 'Direct URL or Google Drive Link',
    'url.placeholder.video': 'YouTube, Vimeo, Drive or Direct MP4',
    'url.help.text': 'Supports sharing links from Google Drive, YouTube, and Vimeo.',
    'search.placeholder': 'Search by name...',
    'filter.title': 'Categories',
    'filter.all': 'All Materials',
    'filter.pdf': 'PDF Documents',
    'filter.image': 'Images',
    'filter.video': 'Videos',
    // User Management
    'tab.materials': 'Materials',
    'tab.users': 'Users',
    'tab.settings': 'Settings',
    'tab.analytics': 'Analytics',
    'user.edit': 'Edit User',
    'user.filter.all': 'All Roles',
    'user.filter.status.all': 'All Statuses',
    'user.status.pending': 'Pending',
    'user.status.active': 'Active',
    'user.status.inactive': 'Inactive',
    'user.status.rejected': 'Rejected',
    'user.action.approve': 'Approve',
    'user.action.reject': 'Reject',
    'user.action.inactivate': 'Deactivate',
    'user.action.delete': 'Delete User',
    'user.invite': 'Registration Invites',
    'user.invite.copy': 'Copy Link',
    'user.invite.copied': 'Copied!',
    'user.access.types': 'File Type Permissions',
    'user.access.hint': 'If none selected, user will have access to all types allowed for their profile.',
    // Communication
    'comm.title': 'Send Message',
    'comm.send': 'Send',
    'comm.success': 'Message sent successfully to N8N flow!',
    'comm.type.email': 'Email',
    'comm.type.whatsapp': 'WhatsApp',
    'comm.email.subject': 'Subject',
    'comm.email.subtitle': 'Subtitle',
    'comm.email.body': 'Email Body',
    'comm.wa.type': 'Message Type',
    'comm.wa.text': 'Text Only',
    'comm.wa.file': 'Text + File',
    'comm.wa.message': 'Message',
    'comm.file.url': 'File/Attachment URL',
    // Confirmation Modal
    'confirm.delete.title': 'Confirm Deletion',
    'confirm.delete.message': 'Are you sure you want to delete this item? This action cannot be undone.',
    'confirm.delete.confirm': 'Yes, Delete',
    // Analytics
    'analytics.total.views': 'Total Views',
    'analytics.unique.users': 'Unique Users',
    'analytics.top.material': 'Most Viewed Material',
    'analytics.col.views': 'Views',
    'analytics.col.users': 'Users',
    'analytics.col.last_access': 'Last Access',
    'analytics.detail.title': 'Access History',
    'analytics.detail.user': 'User',
    'analytics.detail.date': 'Date/Time',
    'analytics.detail.lang': 'Language',
    'analytics.empty': 'No access logs recorded yet.',
    'analytics.rank.materials': 'Top 5 Materials',
    'analytics.rank.users': 'Top 5 Active Users',
    'analytics.filter.type': 'Filter by Document Type',
    'analytics.filter.role': 'Filter by User Role',
  },
  'es-es': {
    'app.title': 'MaterialShare Pro',
    'auth.login': 'Acceso',
    'auth.register': 'Registrarse',
    'auth.hint': 'Cuentas Demo: admin@demo.com, client@demo.com, distributor@demo.com, consultant@demo.com (Clave: 123456)',
    // Landing Page Texts
    'landing.client.title': 'Bienvenido al Área del Cliente',
    'landing.client.desc': 'Obtenga acceso exclusivo a toda la documentación técnica y novedades de nuestros productos.',
    'landing.client.benefit.1': 'Descarga de Manuales y Certificados',
    'landing.client.benefit.2': 'Visualización de Catálogos en Alta Definición',
    'landing.client.benefit.3': 'Acceso a Videos de Instrucción y Uso',

    'landing.distributor.title': 'Portal del Socio Distribuidor',
    'landing.distributor.desc': 'Acelere sus ventas con herramientas de marketing y tablas comerciales actualizadas.',
    'landing.distributor.benefit.1': 'Acceso a Listas de Precios Confidenciales',
    'landing.distributor.benefit.2': 'Descarga de Kits de Marketing (Posts, Banners)',
    'landing.distributor.benefit.3': 'Prioridad en Lanzamientos de Productos',

    'landing.consultant.title': 'Academia de Ventas',
    'landing.consultant.desc': 'Domine el portafolio y cierre más negocios con nuestros materiales de apoyo.',
    'landing.consultant.benefit.1': 'Entrenamientos Técnicos y Comerciales',
    'landing.consultant.benefit.2': 'Guiones de Ventas y Argumentación',
    'landing.consultant.benefit.3': 'Materiales de Apoyo para Presentaciones',

    'dashboard.title': 'Materiales Disponibles',
    'admin.title': 'Panel de Administración',
    'common.logout': 'Cerrar Sesión',
    'role.client': 'Cliente',
    'role.distributor': 'Distribuidor',
    'role.consultant': 'Consultor',
    'role.super_admin': 'Súper Admin',
    'material.type.pdf': 'Documento PDF',
    'material.type.image': 'Imagen',
    'material.type.video': 'Video',
    'no.materials': 'No se encontraron materiales con los filtros actuales.',
    'add.material': 'Añadir Material',
    'edit.material': 'Editar Material',
    'delete': 'Eliminar',
    'edit': 'Editar',
    'view': 'Ver',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'title': 'Título',
    'type': 'Tipo',
    'permissions': 'Permisos',
    'actions': 'Acciones',
    'status': 'Estado',
    'active': 'Activo',
    'inactive': 'Inactivo',
    'manage.assets': 'Gestionar Archivos',
    'asset.url': 'URL del Archivo',
    'asset.subtitle': 'URL del Subtítulo',
    'edit.assets.title': 'Gestionar Versiones: ',
    'empty.url.hint': 'Deje la URL vacía para eliminar la versión de este idioma.',
    'url.placeholder.pdf': 'URL directa o Link de Google Drive',
    'url.placeholder.image': 'URL directa o Link de Google Drive',
    'url.placeholder.video': 'YouTube, Vimeo, Drive o URL MP4 directa',
    'url.help.text': 'Soporta enlaces de Google Drive, YouTube y Vimeo.',
    'search.placeholder': 'Buscar por nombre...',
    'filter.title': 'Categorías',
    'filter.all': 'Todos los Materiales',
    'filter.pdf': 'Documentos PDF',
    'filter.image': 'Imágenes',
    'filter.video': 'Videos',
    // User Management
    'tab.materials': 'Materiales',
    'tab.users': 'Usuarios',
    'tab.settings': 'Configuración',
    'tab.analytics': 'Métricas',
    'user.edit': 'Editar Usuario',
    'user.filter.all': 'Todos los Perfiles',
    'user.filter.status.all': 'Todos los Estados',
    'user.status.pending': 'Pendiente',
    'user.status.active': 'Activo',
    'user.status.inactive': 'Inactivo',
    'user.status.rejected': 'Rechazado',
    'user.action.approve': 'Aprobar',
    'user.action.reject': 'Rechazar',
    'user.action.inactivate': 'Desactivar',
    'user.action.delete': 'Eliminar Usuario',
    'user.invite': 'Invitaciones de Registro',
    'user.invite.copy': 'Copiar Enlace',
    'user.invite.copied': '¡Copiado!',
    'user.access.types': 'Permisos de Tipos de Archivo',
    'user.access.hint': 'Si no selecciona ninguno, el usuario tendrá acceso a todos los tipos permitidos para su perfil.',
    // Communication
    'comm.title': 'Enviar Mensaje',
    'comm.send': 'Enviar',
    'comm.success': '¡Mensaje enviado con éxito al flujo N8N!',
    'comm.type.email': 'Email',
    'comm.type.whatsapp': 'WhatsApp',
    'comm.email.subject': 'Asunto',
    'comm.email.subtitle': 'Subtítulo',
    'comm.email.body': 'Cuerpo del Email',
    'comm.wa.type': 'Tipo de Mensaje',
    'comm.wa.text': 'Solo Texto',
    'comm.wa.file': 'Texto + Arquivo',
    'comm.wa.message': 'Mensaje',
    'comm.file.url': 'URL del Archivo/Adjunto',
    // Confirmation Modal
    'confirm.delete.title': 'Confirmar Eliminación',
    'confirm.delete.message': '¿Está seguro de que desea eliminar este elemento? Esta acción es irreversible.',
    'confirm.delete.confirm': 'Sí, Eliminar',
    // Analytics
    'analytics.total.views': 'Vistas Totales',
    'analytics.unique.users': 'Usuarios Únicos',
    'analytics.top.material': 'Material Más Visto',
    'analytics.col.views': 'Vistas',
    'analytics.col.users': 'Usuarios',
    'analytics.col.last_access': 'Último Acceso',
    'analytics.detail.title': 'Historial de Acceso',
    'analytics.detail.user': 'Usuario',
    'analytics.detail.date': 'Fecha/Hora',
    'analytics.detail.lang': 'Idioma',
    'analytics.empty': 'Aún no hay registros de acceso.',
    'analytics.rank.materials': 'Top 5 Materiales',
    'analytics.rank.users': 'Top 5 Usuarios Activos',
    'analytics.filter.type': 'Filtrar por Tipo de Documento',
    'analytics.filter.role': 'Filtrar por Perfil de Usuario',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt-br');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};